packages:
  - apps/*
  - packages/*

allowBuilds:
  '@swc/core': true
  protobufjs: true
  sharp: true
  unrs-resolver: true

ignoredBuiltDependencies:
  - sharp

onlyBuiltDependencies:
  - protobufjs
  - unrs-resolver
